version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: ai-virtual-try-on-backend-dev
    ports:
      - "3000:3000"
      - "9229:9229"  # Debug port
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/app/src
      - ./backend/data:/app/data
      - backend_logs:/app/logs
      - backend_node_modules:/app/node_modules
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: ai-virtual-try-on-frontend-dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - frontend_node_modules:/app/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    command: npm run dev

volumes:
  backend_logs:
    driver: local
  backend_node_modules:
    driver: local
  frontend_node_modules:
    driver: local

networks:
  app-network:
    driver: bridge